// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type App struct {
	AppID      int64          `json:"app_id"`
	AppName    string         `json:"app_name"`
	AppCompany string         `json:"app_company"`
	AppVersion string         `json:"app_version"`
	AppStatus  sql.NullInt64  `json:"app_status"`
	AppData    sql.NullString `json:"app_data"`
	CreatedAt  sql.NullInt64  `json:"created_at"`
	UpdatedAt  sql.NullInt64  `json:"updated_at"`
	DeletedAt  sql.NullInt64  `json:"deleted_at"`
}

type Category struct {
	CategoryID          int64          `json:"category_id"`
	CategoryName        string         `json:"category_name"`
	CategoryStatus      int64          `json:"category_status"`
	CategoryDescription sql.NullString `json:"category_description"`
	CategoryProperties  sql.NullString `json:"category_properties"`
	CreatedAt           sql.NullInt64  `json:"created_at"`
	UpdatedAt           sql.NullInt64  `json:"updated_at"`
	DeletedAt           sql.NullInt64  `json:"deleted_at"`
}

type Customer struct {
	CustomerID          int64          `json:"customer_id"`
	CustomerName        string         `json:"customer_name"`
	CustomerEmail       sql.NullString `json:"customer_email"`
	CustomerPhone       string         `json:"customer_phone"`
	CustomerStatus      int64          `json:"customer_status"`
	CustomerTotalOrders int64          `json:"customer_total_orders"`
	CustomerProperties  sql.NullString `json:"customer_properties"`
	CreatedAt           sql.NullInt64  `json:"created_at"`
	UpdatedAt           sql.NullInt64  `json:"updated_at"`
	DeletedAt           sql.NullInt64  `json:"deleted_at"`
}

type Order struct {
	OrderID            int64          `json:"order_id"`
	OrderCode          string         `json:"order_code"`
	OrderCreateAt      int64          `json:"order_create_at"`
	OrderUpdateAt      int64          `json:"order_update_at"`
	OrderStatus        int64          `json:"order_status"`
	OrderTotalAmount   int64          `json:"order_total_amount"`
	OrderTotalDiscount int64          `json:"order_total_discount"`
	OrderProperties    sql.NullString `json:"order_properties"`
	OrderBalance       int64          `json:"order_balance"`
	OrderUserID        int64          `json:"order_user_id"`
	OrderTableID       int64          `json:"order_table_id"`
	OrderCustomerID    int64          `json:"order_customer_id"`
}

type OrderItem struct {
	OdiID          int64 `json:"odi_id"`
	OdiOrderID     int64 `json:"odi_order_id"`
	OdiProductCode int64 `json:"odi_product_code"`
	OdiQuantity    int64 `json:"odi_quantity"`
	OdiPrice       int64 `json:"odi_price"`
	OdiDiscount    int64 `json:"odi_discount"`
}

type Payment struct {
	PaymentID         int64          `json:"payment_id"`
	PaymentOrderID    int64          `json:"payment_order_id"`
	PaymentOrderCode  string         `json:"payment_order_code"`
	PaymentAmount     int64          `json:"payment_amount"`
	PaymentMethod     int64          `json:"payment_method"`
	PaymentStatus     int64          `json:"payment_status"`
	PaymentProperties sql.NullString `json:"payment_properties"`
	CreatedAt         sql.NullInt64  `json:"created_at"`
	UpdatedAt         sql.NullInt64  `json:"updated_at"`
	DeletedAt         sql.NullInt64  `json:"deleted_at"`
}

type Product struct {
	ProductID          int64          `json:"product_id"`
	ProductCode        string         `json:"product_code"`
	ProductName        string         `json:"product_name"`
	ProductDisplayName string         `json:"product_display_name"`
	ProductDescription sql.NullString `json:"product_description"`
	ProductPrice       int64          `json:"product_price"`
	ProductStatus      int64          `json:"product_status"`
	ProductProperties  sql.NullString `json:"product_properties"`
	ProductCategoryID  int64          `json:"product_category_id"`
	CreatedAt          sql.NullInt64  `json:"created_at"`
	UpdatedAt          sql.NullInt64  `json:"updated_at"`
	DeletedAt          sql.NullInt64  `json:"deleted_at"`
}

type Rule struct {
	RuleID         int64          `json:"rule_id"`
	RuleName       string         `json:"rule_name"`
	RuleCode       string         `json:"rule_code"`
	RuleType       int64          `json:"rule_type"`
	RuleStatus     int64          `json:"rule_status"`
	RuleProperties sql.NullString `json:"rule_properties"`
	CreatedAt      sql.NullInt64  `json:"created_at"`
	UpdatedAt      sql.NullInt64  `json:"updated_at"`
	DeletedAt      sql.NullInt64  `json:"deleted_at"`
}

type Table struct {
	TableID         int64          `json:"table_id"`
	TableName       string         `json:"table_name"`
	TableCode       string         `json:"table_code"`
	TableStatus     int64          `json:"table_status"`
	TableProperties sql.NullString `json:"table_properties"`
	CreatedAt       sql.NullInt64  `json:"created_at"`
	UpdatedAt       sql.NullInt64  `json:"updated_at"`
	DeletedAt       sql.NullInt64  `json:"deleted_at"`
}

type User struct {
	UserID          int64  `json:"user_id"`
	UserDisplayName string `json:"user_display_name"`
	UserName        string `json:"user_name"`
	UserPhone       string `json:"user_phone"`
	UserPassword    string `json:"user_password"`
	UserStatus      int64  `json:"user_status"`
	UserAvatar      string `json:"user_avatar"`
	UserRoleID      int64  `json:"user_role_id"`
	CreatedAt       int64  `json:"created_at"`
	UpdatedAt       int64  `json:"updated_at"`
	DeletedAt       int64  `json:"deleted_at"`
	LastLoginAt     int64  `json:"last_login_at"`
	LoginTimes      int64  `json:"login_times"`
}
