package uconst

const (
	CUSTOMER_STATUS_INACTIVE = COMMON_STATUS_INACTIVE
	CUSTOMER_STATUS_ACTIVE   = COMMON_STATUS_ACTIVE
	CUSTOMER_STATUS_DELETED  = COMMON_STATUS_DELETED
)

var CUSTOMER_STATUS_OPTIONS = map[int]string{
	CUSTOMER_STATUS_INACTIVE: "Inactive",
	CUSTOMER_STATUS_ACTIVE:   "Active",
	CUSTOMER_STATUS_DELETED:  "Deleted",
}
