# Common messages
success: "Success"
internal_server_error: "Internal Server Error"
check_constraint: "Check constraint fails"
unique_constraint: "Duplicate entry"
foreign_key_constraint: "Cannot delete or update a parent row: a foreign key constraint fails"

# Authentication messages
require_auth: "Authorization header is required"
unauthorized: "Token is invalid or expired"
forbidden: "You don't have permission to access this resource"
login_success: "Login successfully"
invalid_login: "Username or password is incorrect"
logout_success: "Logout successfully"
login_failed: "Login failed"
logout_failed: "Logout failed"


# Validate messages
invalid_email: "Invalid email"
invalid_password: "Invalid password"
invalid_params: "Invalid parameters"


# User messages
user_not_found: "User not found"
user_already_exists: "User already exists"
user_created: "User created successfully"
user_updated: "User updated successfully"
user_deleted: "User deleted successfully"
user_password_updated: "Password updated successfully"
user_password_not_match: "Password does not match"
user_password_reset: "Password reset successfully"
user_password_reset_token_invalid: "Password reset token is invalid or expired"
user_password_reset_token_required: "Password reset token is required"
user_password_reset_token_not_match: "Password reset token does not match"


