package constants

const (
	BOOL_TRUE  = true
	BOOL_FALSE = false

	// COMMON_STATUS
	COMMON_STATUS_DEFAULT  = 0
	COMMON_STATUS_INACTIVE = 1
	COMMON_STATUS_ACTIVE   = 2
	COMMON_STATUS_DELETED  = 3
	COMMON_STATUS_DRAF     = 7
	COMMON_STATUS_PENDING  = 4
	COMMON_STATUS_COMPLETE = 9
	COMMON_STATUS_CANCEL   = 10
)

var COMMON_STATUS_OPTIONS = map[int]string{
	COMMON_STATUS_INACTIVE: "Inactive",
	COMMON_STATUS_ACTIVE:   "Active",
	COMMON_STATUS_DELETED:  "Deleted",
	COMMON_STATUS_DRAF:     "Draf",
	COMMON_STATUS_PENDING:  "Pending",
	COMMON_STATUS_COMPLETE: "Completed",
	COMMON_STATUS_CANCEL:   "Canceled",
}

const (
	// DEFAULT_LIMIT default limit
	DEFAULT_LIMIT = 10
	// DEFAULT_OFFSET default offset
	DEFAULT_OFFSET = 0
	// DEFAULT_SORT default sort
	DEFAULT_SORT = "desc"
	// DEFAULT_PAGE default page
	DEFAULT_PAGE = 1
	// DEFAULT_PAGE_SIZE default page size
	DEFAULT_PAGE_SIZE = 20

	// TYPE_LOG_INFO type log info
	TYPE_LOG_INFO = "info"
	// TYPE_LOG_ERROR type log error
	TYPE_LOG_ERROR = "error"
	// TYPE_LOG_WARN type log warn
	TYPE_LOG_WARN = "warn"
)
