package constants

const (
	FLAG_BYPASS_ROLE      = 0
	USER_DEFAULT_PASSWORD = "pos@123"

	USER_STATUS_INACTIVE = COMMON_STATUS_INACTIVE
	USER_STATUS_ACTIVE   = COMMON_STATUS_ACTIVE
	USER_STATUS_DELETED  = COMMON_STATUS_DELETED

	USER_ROLEID_ADMIN   = 1
	USER_ROLEID_MANAGER = 2
	USER_ROLEID_USER    = 3
)

var USER_STATUS_OPTIONS = map[int]string{
	USER_STATUS_INACTIVE: "Inactive",
	USER_STATUS_ACTIVE:   "Active",
	USER_STATUS_DELETED:  "Deleted",
}

var USER_ROLE_OPTIONS = map[int]string{
	USER_ROLEID_ADMIN:   "Admin",
	USER_ROLEID_USER:    "User",
	USER_ROLEID_MANAGER: "Manager",
}
